import { StyleSheet,Dimensions,Constants } from "react-native";
export const styles = StyleSheet.create({
  marginFix : {
    marginTop : 50,
  },
  topSearchHeader : {
    display : 'flex',
    flexDirection : 'row',
    alignItems : 'center'
  },
  serchBoxContainer:{
    width : '74%',
    marginLeft : "3%",
    marginRight : "3%",
  },
  serchBoxTextInput : {
    borderColor: "#D3D3D3",
    borderWidth: 1,
    borderRadius: 10,
    marginTop: 10,
    marginBottom: 10,
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 10,
    paddingRight: 10,
  },
  addItemToListBox : {
    width : '14%',
    marginLeft : "3%",
    marginRight : "3%",
    display : 'flex',
    alignItems : 'center',
  },
  container : {
    backgroundColor : "#fff",
    height : Dimensions.get('window').height,
    margin : 0,
    // borderColor : '#000',
    // borderWidth : 1,
  },
  topSearchHeaderParentContainer : {
    minHeight: Dimensions.get('window').height*.1,
  },
  heading: {
    marginTop: 100,
    display: "flex",
    alignItems: "center",
  },
  headingText: {
    fontWeight: "bold",
    fontSize: 25,
  },
  boldHorizontalLine: {
    borderColor: "#F9F9F9",
    opacity: 0.7,
    borderWidth: 0,
    height: 1,
    // marginLeft: 30,
    // marginRight: 30,
    marginTop: 10,
    // marginBottom: 10,
    backgroundColor: "#F3E9E5",
    // borderRadius: 5,
    elevation: 10,
  },
  itemItemsContainer: {
    height: Dimensions.get('window').height*.9,
  },
  dottedHorizontalLine: {
    borderColor: "#F3E9E5",
    borderStyle: "dotted",
    borderTopWidth: 2,
    height: 5,
    marginLeft: 30,
    marginRight: 30,
    marginTop: 10,
    marginBottom: 10,
  },
  addItemItemContainer: {
    flexDirection: "row",
    // justifyContent : 'center',
    alignItems: "center",
    borderColor: "#B1E8CE",
    borderWidth: 2,
    borderRadius: 10,
    padding: 10,
    marginLeft: 10,
    marginRight: 10,
    marginTop: 10,
    marginBottom: 10,
    backgroundColor: "#F5F5F5",
  },
  addItemItemTextStyle: {
    fontWeight: "bold",
    fontSize: 18,
  },
  icons: {
    marginLeft: 10,
    marginRight: 10,
  },
  mediumBoldText: {
    fontWeight: "bold",
    fontSize: 20,
  },
  smallBoldText: {
    fontWeight: "bold",
    fontSize: 15,
  },
  smallText: {
    fontSize: 15,
  },
  finalItemListContainerButton: {
    borderColor: "#D3D3D3",
    borderWidth: 1,
    borderRadius: 10,
    marginTop: 10,
    marginBottom: 10,
    marginLeft: 10,
    marginRight: 10,
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 10,
    paddingRight: 10,
    backgroundColor: "#03B660",
    display: "flex",
    alignItems: "center",
  },
  finalItemListContainerButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 20,
  },
});
